language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - 'nightly'

sudo: true

install:
  - pip3 install cleo
  - pip3 install lxml
  - pip3 install coverage

script:
  - cd $TRAVIS_BUILD_DIR
  - unzip -x test/var/lib/20170101\ Grouper\ Tabellen\ v20161117.zip -d test/var/lib/
  - kerapu kerapu:shredder test/var/lib/20170101\ BoomBestanden\ v20161117.xml  test/var/lib/
  - kerapu kerapu:shredder test/var/lib/20170101\ Referenties\ v20161117.xml test/var/lib/
  - python3 -m unittest discover -s test -p *Test.py
